services:
  video-db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      interval: 10s
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - ../.env
    networks:
      - backend

volumes:
  pg_data: